#define COLOR_RESET   "\x1b[0m"
#define COLOR_BOLD   "\x1b[1m"

#define COLOR_BLACK   "\x1b[30m"
#define COLOR_RED     "\x1b[31m"
#define COLOR_GREEN   "\x1b[32m"
#define COLOR_YELLOW  "\x1b[33m"
#define COLOR_BLUE    "\x1b[34m"
#define COLOR_MAGENTA "\x1b[35m"
#define COLOR_CYAN    "\x1b[36m"
#define COLOR_WHITE   "\x1b[37m"

#define COLOR_LIGHT_BLACK   "\x1b[30;1m"
#define COLOR_LIGHT_RED     "\x1b[31;1m"
#define COLOR_LIGHT_GREEN   "\x1b[32;1m"
#define COLOR_LIGHT_YELLOW  "\x1b[33;1m"
#define COLOR_LIGHT_BLUE    "\x1b[34;1m"
#define COLOR_LIGHT_MAGENTA "\x1b[35;1m"
#define COLOR_LIGHT_CYAN    "\x1b[36;1m"
#define COLOR_LIGHT_WHITE   "\x1b[37;1m"